### PR TITLE
replace ncbitaxon altIDs by main taxon ID

### PR DESCRIPTION
**Pull request by marieALaporte**
Not sure if filling only the providedTaxonId column is enough. Should I fill in also the providedTaxonName?

### CODE REVIEW

**Comment by marieALaporte** [comment]
I also noticed that https://github.com/marieALaporte/samara/blob/master/src/main/resources/org/planteome/samara/apsnet/taxonMap.tsv#L3
uses NCBI:9606 instead as NCBITaxon:9606 for the ID

**Comment by jhpoelen** [comment]
since the NCBI id not provided by APS, the verbatim/mapped names are needed to make the desired ncbi mapping explicit. So, for example:

providedId | providedName | resolvedId | resolvedName
--- | --- | --- | ---
[empty] | Homo sapiens | NCBITaxon:9606 | Homo sapiens

Note that both NCBITaxon: and NCBI: prefixes are supported.

**Comment by marieALaporte** [comment]
for the providedTaxonName I took the source taxon name column from the aps scrape file. I hope this is the column I should have used

**Comment by jhpoelen** [comment]
@marieALaporte thanks!

**Pull request merged**
